ci: Use official CouchDB docker image
  The official image on the Docker hub seems to be
  https://hub.docker.com/_/couchdb rather than
  https://hub.docker.com/r/apache/couchdb.

  We try to use this image as the previous cannot be downloaded anymore
  by `podman-machine` which fails with this error:

  ```bash
  Error: error pulling image "apache/couchdb:3.2.2": unable to pull apache/couchdb:3.2.2: 5 errors occurred:
	* Error initializing source docker://apache/couchdb:3.2.2: Error reading manifest 3.2.2 in docker.io/apache/couchdb: manifest unknown: OCI index found, but accept header does not support OCI indexes
	* Error initializing source docker://registry.fedoraproject.org/apache/couchdb:3.2.2: Error reading manifest 3.2.2 in registry.fedoraproject.org/apache/couchdb: manifest unknown: manifest unknown
	* Error initializing source docker://quay.io/apache/couchdb:3.2.2: Error reading manifest 3.2.2 in quay.io/apache/couchdb: unauthorized: access to the requested resource is not authorized
	* Error initializing source docker://registry.access.redhat.com/apache/couchdb:3.2.2: Error reading manifest 3.2.2 in registry.access.redhat.com/apache/couchdb: name unknown: Repo not found
	* Error initializing source docker://registry.centos.org/apache/couchdb:3.2.2: Error reading manifest 3.2.2 in registry.centos.org/apache/couchdb: manifest unknown: manifest unknown
  ```