build: Add missing vuvuzela and cli dependencies
Reported Issue on Ubuntu 14.05 was:

module.js:340
    throw err;
          ^
Error: Cannot find module 'vuvuzela'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/lib/index.js:20:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Origin: https://github.com/TizenTeam/cozy-desktop
Change-Id: If51c4de995d207f56096040eda90eed317532846
Signed-off-by: Philippe Coval <rzr@gna.org>